apiVersion: v1
kind: Service
metadata:
  name: python-flask-app-service
  namespace: default
  labels:
    app: python-flask-app
spec:
  type: NodePort
  selector:
    app: python-flask-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30500
